name: CI Latest Release
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci-latest-release:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Determine platform
        run: |
          if [[ "${{ matrix.runner }}" == *"arm"* ]]; then
            echo "PLATFORM=arm64" >> $GITHUB_ENV
          else
            echo "PLATFORM=amd64" >> $GITHUB_ENV
          fi

      - name: Build a new release based on the code
        run: make release-test PLATFORM=${PLATFORM}

      - name: Diff binaries
        run: diff -u ./release/latest/dns-proxy-action-${PLATFORM} ./release/latest/dns-proxy-action-${PLATFORM}-test || exit 1


