name: CI Latest Release
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci-latest-release:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Determine platform
        run: |
          if [[ "${{ matrix.runner }}" == *"arm"* ]]; then
            echo "PLATFORM=arm64" >> $GITHUB_ENV
          else
            echo "PLATFORM=amd64" >> $GITHUB_ENV
          fi

      - name: Build a new release based on the code
        run: make release-test PLATFORM=${PLATFORM}

      - name: Diff binaries
        run: diff -u ./release/latest/dns-proxy-action-${PLATFORM} ./release/latest/dns-proxy-action-${PLATFORM}-test || exit 1


